#!/bib/bash

SOURCE_DIRECTORY=/tmp/app-logs


R="\e[31m"
G="\e[32m"
Y="\e[33m"
N="\e[0m"

if [ -d $SOURCE_DIRECTORY ]
then
    echo -e  " $G file exists $N"
else
    echo -e " $R create a file  $N"
    exit 1 
fi

FILES=$(find $SOURCE_DIRECTORY -name "*.log" -mtime +14)

echo "file to delete : $FILES"

while ifs= read -r line
do
  echo "deleting the files $line"
  rm -rf $line
done <<< $FILES
